drop table BRANCH_Inre_Oozie;

create External Table BRANCH_Inre_Oozie (

BRANCH_CODE		INT,
BRANCH_NAME		VARCHAR(25),
BRANCH_STREET		VARCHAR(30),
BRANCH_CITY		VARCHAR(30),
BRANCH_STATE		VARCHAR(30),
BRANCH_ZIP 		STRING,
BRANCH_PHONE		VARCHAR(13),
LAST_UPDATED		TIMESTAMP
)

ROW FORMAT DELIMITED
Fields Terminated by '\t'
Stored as textfile 
Location "/user/maria_dev/CREDIT_CARD_SYSTEM/SQOOP_JOB_INCREMENTAL/CDW_SAPP_D_BRANCH/";


drop table CREDIT_CARD_Incre_Oozie;

CREATE EXTERNAL TABLE CREDIT_CARD_Incre_Oozie (

CUST_CC_NO		STRING,
TIMEID			VARCHAR(8),
CUST_SSN		INT,
BRANCH_CODE		INT,
TRANSACTION_TYPE 	VARCHAR(30),
TRANSACTION_VALUE	DECIMAL(20,3),
TRANSACTION_ID		INT
  
)
ROW FORMAT DELIMITED
Fields Terminated by '\t'
Stored as textfile 
Location "/user/maria_dev/CREDIT_CARD_SYSTEM/SQOOP_JOB_INCREMENTAL/CDW_SAPP_F_CREDITCARD/";


drop table CUSTOMER_Incre_Oozie;

CREATE EXTERNAL TABLE CUSTOMER_Incre_Oozie(
CUST_SSN		INT,
CUST_F_NAME		VARCHAR(40),
CUST_M_NAME		VARCHAR(40),
CUST_L_NAME		VARCHAR(40),
CUST_CC_NO		STRING,
CUST_STREET		VARCHAR(38),
CUST_CITY		VARCHAR(30),
CUST_STATE 		VARCHAR(30),
CUST_COUNTRY		VARCHAR(30),
CUST_ZIP		STRING,
CUST_PHONE		VARCHAR(8),
CUST_EMAIL		VARCHAR(40),
LAST_UPDATED		TIMESTAMP
)
ROW FORMAT DELIMITED
Fields Terminated by '\t'
Stored as Textfile
Location "/user/maria_dev/CREDIT_CARD_SYSTEM/SQOOP_JOB_INCREMENTAL/CDW_SAPP_D_CUSTOMER/";

drop table TIMEID_Incre_Oozie;

CREATE External TABLE TIMEID_Incre_Oozie (

TRANSACTION_ID	INT,
TIMEID		VARCHAR(8),
DAY		INT,
MONTH		INT,
QUARTER		VARCHAR(8),
YEAR		INT
)

ROW FORMAT DELIMITED
Fields Terminated by '\t'
Stored as Textfile
Location "/user/maria_dev/CREDIT_CARD_SYSTEM/SQOOP_JOB_INCREMENTAL/CDW_SAPP_D_TIME/";




